# Generated by Django 5.0.2 on 2024-03-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='data',
            new_name='date',
        ),
    ]
